version: '2'

services:

  minecraft:
    image: minecraft:1.14.2
    build:
      context: ./minecraft
      dockerfile: Dockerfile.1.14.2
    ports:
      - 25565:25565
    volumes:
      - ./minecraft/world/1:/minecraft/world
      - ./minecraft/logs/1:/minecraft/logs

  minecraft-forge:
    image: minecraft:1.15.2.forge
    build:
      context: ./minecraft
      dockerfile: Dockerfile.1.15.2.forge
    ports:
      - 25565:25565
    volumes:
      - ./minecraft/world/2:/minecraft/world
      - ./minecraft/logs/2:/minecraft/logs
      - ./minecraft/crash-reports/2:/minecraft/crash-reports

  minecraft-fabric:
    image: minecraft:1.15.2.fabric
    build:
      context: ./minecraft
      dockerfile: Dockerfile.1.15.2.fabric
    ports:
      - 25565:25565
    volumes:
      - ./minecraft/world/1:/minecraft/world
      - ./minecraft/logs/1:/minecraft/logs

  ngrok:
    build:
      context: ./ngrok
      dockerfile: Dockerfile
      args:
        NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
    command: ./ngrok tcp ${NGROK_TARGET_SERVICE}:25565 --region ${NGROK_REGION} --log=stdout
