version: '2'

services:

  minecraft:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/minecraft:1.14.4.fabric
    ports:
      - 25565:25565
    volumes:
      - /minecraft/data:/minecraft/data
    logging:
      driver: awslogs
      options:
        awslogs-group: "/ecs/playground"
        awslogs-region: "${AWS_DEFAULT_REGION}"
        awslogs-stream-prefix: ecs
    command: java -Xmx3584M -Xms3584M -jar ./fabric-server-launch.jar nogui
    volumes:
      - /minecraft/world/1:/minecraft/world
      - /minecraft/logs/1:/minecraft/logs
