FROM java:8-jdk-alpine

USER root

RUN apk update && apk add ca-certificates && update-ca-certificates && apk add openssl

RUN mkdir -m 777 -p /minecraft/data


WORKDIR /minecraft

RUN wget https://launcher.mojang.com/v1/objects/808be3869e2ca6b62378f9f4b33c946621620019/server.jar

RUN java -Xmx1024M -Xms1024M -jar ./server.jar nogui

RUN cp eula.txt eula.txt.bk &&  sed 's/eula=false/eula=true/' ./eula.txt.bk > eula.txt

COPY server.properties ./

CMD java -Xmx1024M -Xms1024M -jar ./server.jar nogui
