FROM java:8-jdk-alpine

RUN apk update && apk add bash

RUN mkdir -p /minecraft/data

WORKDIR /minecraft

ADD https://launcher.mojang.com/v1/objects/808be3869e2ca6b62378f9f4b33c946621620019/server.jar ./

RUN java -Xmx1024M -Xms1024M -jar ./server.jar nogui

RUN cp eula.txt eula.txt.bk &&  sed 's/eula=false/eula=true/' ./eula.txt.bk > eula.txt

COPY server.properties ./

COPY ops.txt ./

CMD java -Xmx1024M -Xms1024M -jar ./server.jar nogui
