# FROM openjdk
FROM java:8-jdk-alpine

RUN apk update && apk add bash

RUN mkdir -p /minecraft/data

WORKDIR /minecraft

ADD https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.15.2-31.1.62/forge-1.15.2-31.1.62-installer.jar ./forge-installer.jar

RUN java -jar ./forge-installer.jar --installServer


# ADD https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.15.2-31.1.62/forge-1.15.2-31.1.62-universal.jar ./
# RUN java -Xmx1024M -Xms1024M -jar ./forge-1.15.2-31.1.62-universal.jar nogui

RUN java -Xmx1024M -Xms1024M -jar ./forge-1.15.2-31.1.62.jar nogui
RUN cp eula.txt eula.txt.bk &&  sed 's/eula=false/eula=true/' ./eula.txt.bk > eula.txt

COPY server.properties ./
COPY ops.txt ./


# industry

## build craft

ADD https://media.forgecdn.net/files/2916/284/AdditionalEnchantedMiner-1.15.2-15.2.6.jar ./mods
ADD https://media.forgecdn.net/files/2871/351/ScalableCatsForce-2.13.1-build-6-with-library.jar ./mods

## mekanism
ADD https://media.forgecdn.net/files/2938/498/Mekanism-1.15.2-9.10.1.414.jar ./mods
ADD https://media.forgecdn.net/files/2938/500/MekanismGenerators-1.15.2-9.10.1.414.jar ./mods
ADD https://media.forgecdn.net/files/2938/502/MekanismAdditions-1.15.2-9.10.1.414.jar ./mods
ADD https://media.forgecdn.net/files/2938/501/MekanismTools-1.15.2-9.10.1.414.jar ./mods

## misc
ADD https://media.forgecdn.net/files/2902/495/titanium-1.15.2-2.3.7.jar ./mods
ADD https://media.forgecdn.net/files/2902/496/industrial-foregoing-1.15.2-2.2.2-28d4a81.jar ./mods
ADD https://media.forgecdn.net/files/2930/693/SolarGeneration-1.15.2-1.2.1.jar ./mods
ADD https://media.forgecdn.net/files/2940/434/refinedstorage-1.8.2.jar ./mods

# structure / world
ADD https://media.forgecdn.net/files/2856/387/ruins-1.15.1.3.jar ./mods
ADD https://media.forgecdn.net/files/2904/832/minecolonies-0.10.771-RELEASE-universal.jar ./mods
ADD https://media.forgecdn.net/files/2905/203/structurize-0.10.282-RELEASE.jar ./mods
ADD https://media.forgecdn.net/files/2936/557/themidnight-0.5.7-2.jar ./mods
ADD https://media.forgecdn.net/files/2905/438/valhelsia_structures-15.0.2a.jar ./mods
ADD https://media.forgecdn.net/files/2908/603/lostcities-1.15-3.0.1-alpha.jar ./mods

# tool
ADD https://media.forgecdn.net/files/2895/173/u_team_core-1.15.2-2.11.0.156.jar ./mods
ADD https://media.forgecdn.net/files/2883/653/useful_backpacks-1.15.2-1.9.4.63.jar ./mods
ADD https://media.forgecdn.net/files/2940/577/ForgeEndertech-1.15.2-6.0.2.2-build.0030.jar ./mods
ADD https://media.forgecdn.net/files/2886/618/AdHooks-1.15.2-5.0.0.0-build.0004.jar ./mods

# misc
ADD https://media.forgecdn.net/files/2788/189/InstantLava_1.13.2-1.1.1.jar ./mods


CMD java -server -Xmx1024M -Xms1024M -XX:+UseG1GC -XX:+DisableExplicitGC -XX:+UseStringDeduplication -jar ./forge-1.15.2-31.1.62.jar nogui