FROM java:8-jdk-alpine

RUN apk update && apk add bash

RUN mkdir -p /minecraft/data

WORKDIR /minecraft

ADD https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2838/forge-1.12.2-14.23.5.2838-installer.jar ./forge-installer.jar

RUN java -jar ./forge-installer.jar --installServer

RUN java -Xmx1024M -Xms1024M -jar ./forge-1.12.2-14.23.5.2838-universal.jar nogui

RUN cp eula.txt eula.txt.bk &&  sed 's/eula=false/eula=true/' ./eula.txt.bk > eula.txt

COPY server.properties ./

COPY ops.txt ./

# sample of mods addition
ADD https://media.forgecdn.net/files/2714/302/journeymap-1.12.2-5.5.5b7.jar ./mods
ADD https://media.forgecdn.net/files/2702/41/buildcraft-all-7.99.24.1.jar ./mods
ADD https://media.forgecdn.net/files/2618/630/CodeChickenLib-1.12.2-3.2.2.353-universal.jar ./mods
ADD https://media.forgecdn.net/files/2661/99/ForgeMultipart-1.12.2-2.6.1.81-universal.jar ./mods
ADD https://media.forgecdn.net/files/2572/409/MrTJPCore-1.12.2-2.1.3.35-universal.jar ./mods
ADD https://media.forgecdn.net/files/2572/423/ProjectRed-1.12.2-4.9.1.92-Base.jar ./mods
ADD https://media.forgecdn.net/files/2572/427/ProjectRed-1.12.2-4.9.1.92-integration.jar ./mods
ADD https://media.forgecdn.net/files/2572/422/ProjectRed-1.12.2-4.9.1.92-mechanical.jar ./mods
ADD https://media.forgecdn.net/files/2478/952/ComputerCraft1.80pr1.jar ./mods
CMD java -Xmx1024M -Xms1024M -jar ./forge-1.12.2-14.23.5.2838-universal.jar nogui
